[Variables]

[m1000]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/1.92))
IfEqualValue=(Round(#SCREENAREAWIDTH#/1.92))
IfEqualAction=[!WriteKeyValue Variables size1000 [m1000] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m500]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/3.84))
IfEqualValue=(Round(#SCREENAREAWIDTH#/3.84))
IfEqualAction=[!WriteKeyValue Variables size500 [m500] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m400]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/4.8))
IfEqualValue=(Round(#SCREENAREAWIDTH#/4.8))
IfEqualAction=[!WriteKeyValue Variables size400 [m400] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m300]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/6.4))
IfEqualValue=(Round(#SCREENAREAWIDTH#/6.4))
IfEqualAction=[!WriteKeyValue Variables size300 [m300] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m250]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/7.68))
IfEqualValue=(Round(#SCREENAREAWIDTH#/7.68))
IfEqualAction=[!WriteKeyValue Variables size250 [m250] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m200]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/9.6))
IfEqualValue=(Round(#SCREENAREAWIDTH#/9.6))
IfEqualAction=[!WriteKeyValue Variables size200 [m200] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m150]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/12.8))
IfEqualValue=(Round(#SCREENAREAWIDTH#/12.8))
IfEqualAction=[!WriteKeyValue Variables size150 [m150] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m125]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/15.36))
IfEqualValue=(Round(#SCREENAREAWIDTH#/15.36))
IfEqualAction=[!WriteKeyValue Variables size125 [m125] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m100]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/19.2))
IfEqualValue=(Round(#SCREENAREAWIDTH#/19.2))
IfEqualAction=[!WriteKeyValue Variables size100 [m100] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m95]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/20.2))
IfEqualValue=(Round(#SCREENAREAWIDTH#/20.2))
IfEqualAction=[!WriteKeyValue Variables size95 [m95] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m90]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/21.3))
IfEqualValue=(Round(#SCREENAREAWIDTH#/21.3))
IfEqualAction=[!WriteKeyValue Variables size90 [m90] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m85]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/22.59))
IfEqualValue=(Round(#SCREENAREAWIDTH#/22.59))
IfEqualAction=[!WriteKeyValue Variables size85 [m85] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m80]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/24))
IfEqualValue=(Round(#SCREENAREAWIDTH#/24))
IfEqualAction=[!WriteKeyValue Variables size80 [m80] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m75]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/25.6))
IfEqualValue=(Round(#SCREENAREAWIDTH#/25.6))
IfEqualAction=[!WriteKeyValue Variables size75 [m75] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m70]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/27.43))
IfEqualValue=(Round(#SCREENAREAWIDTH#/27.43))
IfEqualAction=[!WriteKeyValue Variables size70 [m70] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m65]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/29.54))
IfEqualValue=(Round(#SCREENAREAWIDTH#/29.54))
IfEqualAction=[!WriteKeyValue Variables size65 [m65] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m60]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/32))
IfEqualValue=(Round(#SCREENAREAWIDTH#/32))
IfEqualAction=[!WriteKeyValue Variables size60 [m60] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m55]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/35))
IfEqualValue=(Round(#SCREENAREAWIDTH#/35))
IfEqualAction=[!WriteKeyValue Variables size55 [m55] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m50]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/38.4))
IfEqualValue=(Round(#SCREENAREAWIDTH#/38.4))
IfEqualAction=[!WriteKeyValue Variables size50 [m50] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m45]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/42.7))
IfEqualValue=(Round(#SCREENAREAWIDTH#/42.7))
IfEqualAction=[!WriteKeyValue Variables size45 [m45] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m40]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/48))
IfEqualValue=(Round(#SCREENAREAWIDTH#/48))
IfEqualAction=[!WriteKeyValue Variables size40 [m40] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m35]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/54.857))
IfEqualValue=(Round(#SCREENAREAWIDTH#/54.857))
IfEqualAction=[!WriteKeyValue Variables size35 [m35] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m30]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/64))
IfEqualValue=(Round(#SCREENAREAWIDTH#/64))
IfEqualAction=[!WriteKeyValue Variables size30 [m30] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m25]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/76.8))
IfEqualValue=(Round(#SCREENAREAWIDTH#/76.8))
IfEqualAction=[!WriteKeyValue Variables size25 [m25] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m20]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/96))
IfEqualValue=(Round(#SCREENAREAWIDTH#/96))
IfEqualAction=[!WriteKeyValue Variables size20 [m20] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m15]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/128))
IfEqualValue=(Round(#SCREENAREAWIDTH#/128))
IfEqualAction=[!WriteKeyValue Variables size15 [m15] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m12]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/160))
IfEqualValue=(Round(#SCREENAREAWIDTH#/160))
IfEqualAction=[!WriteKeyValue Variables size12 [m12] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m10]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/192))
IfEqualValue=(Round(#SCREENAREAWIDTH#/192))
IfEqualAction=[!WriteKeyValue Variables size10 [m10] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m6]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/320))
IfEqualValue=(Round(#SCREENAREAWIDTH#/320))
IfEqualAction=[!WriteKeyValue Variables size6 [m6] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]
[m5]
Measure=Calc
Formula=(Round(#SCREENAREAWIDTH#/384))
IfEqualValue=(Round(#SCREENAREAWIDTH#/384))
IfEqualAction=[!WriteKeyValue Variables size5 [m5] "#@#S.inc"][!DisableMeasure "#CURRENTSECTION#"]