[SB1]
Measure=Calc
Formula=MBand1
AverageSize=#AverageSize#
Group=Spectrum

[SB2]
Measure=Calc
Formula=MBand2
AverageSize=#AverageSize#
Group=Spectrum

[SB3]
Measure=Calc
Formula=MBand3
AverageSize=#AverageSize#
Group=Spectrum

[SB4]
Measure=Calc
Formula=MBand4
AverageSize=#AverageSize#
Group=Spectrum

[SB5]
Measure=Calc
Formula=MBand5
AverageSize=#AverageSize#
Group=Spectrum

[SB6]
Measure=Calc
Formula=MBand6
AverageSize=#AverageSize#
Group=Spectrum

[SB7]
Measure=Calc
Formula=MBand7
AverageSize=#AverageSize#
Group=Spectrum

[SB8]
Measure=Calc
Formula=MBand8
AverageSize=#AverageSize#
Group=Spectrum

[SB9]
Measure=Calc
Formula=MBand9
AverageSize=#AverageSize#
Group=Spectrum

[SB10]
Measure=Calc
Formula=MBand10
AverageSize=#AverageSize#
Group=Spectrum

[SB11]
Measure=Calc
Formula=MBand11
AverageSize=#AverageSize#
Group=Spectrum

[SB12]
Measure=Calc
Formula=MBand12
AverageSize=#AverageSize#
Group=Spectrum

[SB13]
Measure=Calc
Formula=MBand13
AverageSize=#AverageSize#
Group=Spectrum

[SB14]
Measure=Calc
Formula=MBand14
AverageSize=#AverageSize#
Group=Spectrum

[SB15]
Measure=Calc
Formula=MBand15
AverageSize=#AverageSize#
Group=Spectrum

[SB16]
Measure=Calc
Formula=MBand16
AverageSize=#AverageSize#
Group=Spectrum

[SB17]
Measure=Calc
Formula=MBand17
AverageSize=#AverageSize#
Group=Spectrum

[SB18]
Measure=Calc
Formula=MBand18
AverageSize=#AverageSize#
Group=Spectrum

[SB19]
Measure=Calc
Formula=MBand19
AverageSize=#AverageSize#
Group=Spectrum

[SB20]
Measure=Calc
Formula=MBand20
AverageSize=#AverageSize#
Group=Spectrum
