[BtnStyle]
X=5R
Y=r
W=25
H=25
UpdateDivider=-1

[Btn1]
Meter=Button
SolidColor=30,74,93
X=15
Y=40
W=25
H=25
LeftMouseDownAction=!ActivateConfig "#CURRENTCONFIG#" "1.ini"
UpdateDivider=-1

[Btn2]
Meter=Button
MeterStyle=BtnStyle
SolidColor=31,55,71
LeftMouseDownAction=!ActivateConfig "#CURRENTCONFIG#" "2.ini"

[Btn3]
Meter=Button
MeterStyle=BtnStyle
SolidColor=30,74,93
LeftMouseDownAction=!ActivateConfig "#CURRENTCONFIG#" "3.ini"

[Btn4]
Meter=Button
MeterStyle=BtnStyle
SolidColor=31,55,71
LeftMouseDownAction=!ActivateConfig "#CURRENTCONFIG#" "4.ini"

[Btn5]
Meter=Button
MeterStyle=BtnStyle
SolidColor=30,74,93
LeftMouseDownAction=!ActivateConfig "#CURRENTCONFIG#" "5.ini"